### ISSUE TITLE
TypeError in crp

### ISSUE THREAD

**Issue by matarG** [pennmem/pybeh#6]
I am getting a TypeError when trying to use crp:

```pytb
Traceback (most recent call last):
  File "<pyshell#285>", line 1, in <module>
    crp.crp(recalls = matrix, subjects = sub, listLength = 16,lag_num = 15, skip_first_n=0)
  File "C:\Python27\lib\site-packages\pybeh\crp.py", line 95, in crp
    pt = np.array([trans for trans in range(1 - rec, listLength + 1 - rec) if rec + trans not in seen], dtype=int)
TypeError: unsupported operand type(s) for -: 'int' and 'numpy.string_'
```

coudnt find a solution...
thanks!

**Comment by mivade** [comment]
Please include the code you are using that results in this error.

**Comment by matarG** [comment]
`crp.crp(recalls=recall_matrix, subjects=subjects, listLength=16, lag_num=15, skip_first_n=0)`

when recall_matrix is: `matrix([[u'word_remmb', u'place_screen'],
        [u'\u05e9\u05d9\u05d3\u05d4', u'3'],
        [u'\u05e4\u05d5\u05e9\u05e2 ', u''],
        [u'\u05ea\u05e4\u05d5\u05d6', u'16'],
        [u'\u05d1\u05d3\u05d9\u05d7\u05d4', u'14'],
        [u'\u05de\u05d8\u05d1\u05d7', u'13'],
        [u'\u05e7\u05d5\u05e9\u05d9\u05d4', u'9'],
        [u'\u05de\u05db\u05ea\u05d1', u'12'],
        [u'\u05ea\u05e2\u05e8 ', u''],
        [u'\u05e0\u05e9\u05d9\u05e7\u05d4', u'3'],
        [u'\u05d2\u05d5\u05e3', u'10'],
        [u'\u05de\u05d5\u05e0\u05d9\u05ea', u'8'],
        [u'\u05e8\u05db\u05d1\u05ea', u'6'],
        [u' \u05d8\u05e0\u05e7', u''],
        [u'\u05d4\u05d2\u05e0\u05d4', u'13'],
        [u'\u05d3\u05de\u05d5\u05ea', u'1'],
        [u'\u05d1\u05e7\u05ea\u05d4', u'12'],
        [u'\u05e1\u05e0\u05e4\u05d9\u05e8', u'4'],
        [u'\u05ea\u05e8\u05d9\u05e1', u'11'],
        [u'\u05de\u05e6\u05d5\u05e3', u'10'],
        [u'\u05ea\u05d5\u05ea\u05d7 ', u''],
        [u'\u05d5\u05e8\u05d3', u'13'],
        [u'\u05de\u05e0\u05e2\u05d5\u05dc', u'4'],
        [u'\u05d1\u05d9\u05ea', u'16'],
        [u'\u05d0\u05e8\u05e0\u05e7', u'11'],
        [u'\u05e4\u05e1\u05d2\u05d4', u'3'],
        [u'\u05d2\u05d9\u05dc\u05d9\u05d5\u05df', u'10'],
        [u'\u05e9\u05d5\u05de\u05e2', u'14'],
        [u'\u05d0\u05d3\u05de\u05d4', u'1'],
        [u'\u05de\u05d3\u05e8\u05db\u05d4', u'9'],
        [u'\u05e8\u05d7\u05d5\u05d1', u'14'],
        [u'\u05d1\u05e7\u05ea\u05d4', u'12'],
        [u'\u05e7\u05de\u05d7', u'2'],
        [u'\u05d0\u05e4\u05d9\u05d9\u05d4', u''],
        [u'\u05e7\u05e4\u05d4', u'11'],
        [u'\u05d7\u05d3\u05e7', u'1'],
        [u'\u05d6\u05d9\u05e7\u05d9\u05ea', u'2'],
        [u'\u05de\u05e1\u05e2\u05d3\u05d4', u'8'],
        [u'\u05de\u05e1\u05d3\u05e8\u05d5\u05df', u'15'],
        [u'\u05de\u05e6\u05d1', u'4'],
        [u'\u05e4\u05e2\u05de\u05d5\u05e0\u05d9\u05dd', u''],
        [u'\u05d8\u05d9\u05dc', u'12'],
        [u'\u05e8\u05e9\u05e2', u'5'],
        [u'\u05de\u05db\u05d5\u05e0\u05d9\u05ea', u'10'],
        [u'\u05d3\u05d5\u05db\u05df', u'6'],
        [u'\u05d7\u05dc\u05de\u05d5\u05df', u'5'],
        [u'\u05d0\u05e7\u05d5\u05e8\u05d3\u05d9\u05d5\u05df', u'2'],
        [u'\u05ea\u05d5\u05e3', u'16'],
        [u'\u05e0\u05d6\u05d9\u05e8', u'3'],
        [u'\u05e9\u05de\u05d0\u05dc', u'1'],
        [u'\u05d0\u05d2\u05d5\u05d3\u05dc', u'10'],
        [u'\u05e6\u05e0\u05d7\u05df', u'12'],
        [u'\u05d7\u05d9\u05d9\u05dc', u'1'],
        [u'\u05e8\u05d5\u05d1\u05d4', u'5'],
        [u'\u05db\u05d5\u05de\u05e8', u'2'],
        [u'\u05d7\u05e0\u05d5\u05db\u05d9\u05d9\u05d4', u'3'],
        [u'\u05e6\u05e2\u05e6\u05d5\u05e2', u'16'],
        [u'\u05d0\u05e8\u05e0\u05d1\u05ea', u'14'],
        [u'\u05e0\u05d2\u05e8', u'16'],
        [u'\u05d0\u05d5\u05d5\u05d9\u05e8', u'6'],
        [u'\u05e7\u05d9\u05e9\u05d5\u05d0', u'1'],
        [u'\u05e8\u05e2\u05e9', u'9'],
        [u'\u05d4\u05ea\u05e2\u05de\u05dc\u05d5\u05ea', u'10'],
        [u'\u05de\u05e7\u05e7', u'1'],
        [u'\u05d0\u05d9\u05db\u05e8', u'13'],
        [u'\u05d0\u05e1\u05e4\u05e1\u05d5\u05e3', u'14'],
        [u'\u05e9\u05d5\u05d8\u05e8', u'8'],
        [u'\u05d4\u05e0\u05d0\u05d4', u'3'],
        [u'\u05e7\u05e8\u05d7\u05ea', u'16'],
        [u'\u05e1\u05ea\u05d9\u05d5', u'10'],
        [u'\u05de\u05e9\u05e4\u05d7\u05d4', u'15'],
        [u'\u05e2\u05db\u05d1\u05d9\u05e9', u'11'],
        [u'\u05e4\u05e1\u05e0\u05ea\u05e8', u'9'],
        [u'\u05e2\u05d3\u05d9\u05e0\u05d5\u05ea', u'5'],
        [u'\u05d0\u05e8\u05de\u05d5\u05df', u'3'],
        [u'\u05db\u05d1\u05d9\u05e9', u'2'],
        [u'\u05de\u05d8\u05d5\u05e1', u'1'],
        [u'\u05ea\u05de\u05d5\u05e0\u05d4', u'9'],
        [u'\u05de\u05d1\u05d5\u05db\u05d4', u'11'],
        [u'\u05d7\u05d5\u05ea\u05e0\u05ea', u'8'],
        [u'\u05d0\u05d5\u05e8\u05d5\u05d5\u05d4', u'1'],
        [u'\u05ea\u05d9\u05e0\u05d5\u05e7', u'2'],
        [u'\u05d1\u05d5\u05d1\u05d4', u'9'],
        [u'\u05e4\u05d7\u05dd', u'4'],
        [u'\u05e6\u05e8\u05e6\u05e8', u'8'],
        [u'\u05d6\u05db\u05d5\u05db\u05d9\u05ea', u'12'],
        [u'\u05e4\u05e8\u05e4\u05e8', u'11'],
        [u'\u05d7\u05d9\u05dc\u05d6\u05d5\u05df', u'9'],
        [u'\u05e2\u05db\u05d1\u05e8', u'12'],
        [u'\u05d4\u05e9\u05db\u05de\u05d4', u'10'],
        [u'\u05db\u05d5\u05d1\u05e2', u'15'],
        [u'\u05e7\u05d4\u05dc', u'2'],
        [u'\u05d7\u05e9\u05d1\u05d5\u05df', u'3'],
        [u'\u05e1\u05d9\u05e0\u05d5\u05e8', u'16'],
        [u'\u05d0\u05e4\u05d5\u05d3\u05d4', u'6'],
        [u'\u05e2\u05d8\u05dc\u05e3', u'7'],
        [u'\u05d4\u05dc\u05e6\u05d4', u'4'],
        [u'\u05d0\u05d9\u05d2\u05dc\u05d5', u'10'],
        [u'\u05e0\u05de\u05e8', u'11'],
        [u'\u05d2\u05e8\u05d5\u05df', u'15'],
        [u'\u05d1\u05d5\u05e8\u05d2', u'16'],
        [u'\u05ea\u05e2\u05e0\u05d5\u05d2', u'2'],
        [u'\u05de\u05d0\u05d6\u05e0\u05d9\u05d9\u05dd', u'1'],
        [u'\u05e0\u05d3\u05d1\u05d4', u'5'],
        [u'\u05e8\u05d7\u05de\u05d9\u05dd', u'3'],
        [u'\u05e0\u05d3\u05d1\u05d4', u'5'],
        [u'\u05e0\u05de\u05e8', u'11'],
        [u'\u05d3\u05dc\u05ea', u'1'],
        [u'\u05d7\u05de\u05d0\u05d4', u'12'],
        [u'\u05d0\u05e8\u05d5\u05df', u'2'],
        [u'\u05e2\u05e6\u05d9\u05dd', u''],
        [u'\u05d0\u05d5\u05e8\u05d5\u05d5\u05d4', u'1'],
        [u'\u05de\u05d2\u05dc', u'15'],
        [u'\u05e2\u05d2\u05dc', u'1'],
        [u'\u05db\u05dc\u05d1', u'8'],
        [u'\u05d6\u05e0\u05d1', u'5'],
        [u'\u05e7\u05d9\u05e8', u'2'],
        [u'\u05d9\u05d3\u05d9\u05d3', u'16'],
        [u'\u05e7\u05e9\u05d9\u05e9', u'9'],
        [u'\u05e7\u05d9\u05e8', u'2'],
        [u'\u05e9\u05d9\u05d0', u'9'],
        [u'\u05e2\u05d2\u05d9\u05dc', u'3'],
        [u'\u05de\u05d7\u05e8\u05d5\u05d6\u05ea', u'8'],
        [u'\u05d2\u05d3\u05d5\u05d3', u'1'],
        [u'\u05d1\u05d5\u05e5', u'6'],
        [u'\u05d7\u05d9\u05e8\u05d5\u05ea', u'14'],
        [u'\u05d1\u05e6\u05e7', u'12'],
        [u'\u05db\u05d5\u05e0\u05e0\u05d9\u05ea', u'4'],
        [u'\u05d2\u05d1\u05e2\u05d4', u'7'],
        [u'\u05e8\u05d0\u05d9', u'16'],
        [u'\u05e1\u05d1\u05d0', u'8'],
        [u'\u05de\u05e8\u05ea\u05e3', u'10'],
        [u'\u05de\u05db\u05d5\u05dc\u05ea', u'9'],
        [u'\u05d1\u05d4\u05dc\u05d4', u'14'],
        [u'\u05de\u05d3\u05e3', u'15'],
        [u'\u05d0\u05d6\u05e8\u05d7', u'4'],
        [u'\u05db\u05d9\u05e1\u05d0', u'7'],
        [u'\u05d7\u05d5\u05e4\u05e9', u''],
        [u'\u05e6\u05e8\u05d9\u05e3', u'2'],
        [u'\u05d2\u05d9\u05d1\u05d5\u05e8', u'1'],
        [u'\u05e1\u05d5\u05db\u05e8\u05d9\u05d9\u05d4', u'6'],
        [u'\u05e5', u''],
        [u'\u05d7\u05de\u05e1\u05d9\u05df', u'8'],
        [u'\u05e7\u05d9\u05e5', u'3'],
        [u'\u05e1\u05db\u05d9\u05df', u'13'],
        [u'\u05d0\u05d5\u05dc\u05e8', u'1'],
        [u'\u05de\u05e6\u05e7\u05ea', u'15'],
        [u'\u05d9\u05d5\u05d2\u05d5\u05e8\u05d8', u'7'],
        [u'\u05e7\u05d9\u05e0\u05d5\u05d7', u'10'],
        [u'\u05ea\u05db\u05e9\u05d9\u05d8', u'12'],
        [u'\u05e1\u05e0\u05d3\u05dc\u05e8', u'2'],
        [u'\u05d4\u05d5\u05d5\u05d4', u'5'],
        [u'\u05db\u05d9\u05e0\u05d5\u05e8', u'14'],
        [u'\u05d2\u05d9\u05d8\u05e8\u05d4', u'9'],
        [u'\u05d1\u05e0\u05e0\u05d4', u'10'],
        [u'\u05d0\u05d5\u05e4\u05e7', u'13'],
        [u'\u05e2\u05d1\u05d3\u05d5\u05ea', u'11'],
        [u'\u05d2\u05e8\u05d6\u05df', u'16']], dtype='<U12')`

and subjects is: `[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]`

**Comment by jpazdera** [comment]
The recalls matrix is assumed to be a matrix of integers where each row represents one word list, and each column represents one recalled item. Each entry should be an integer indicating the serial position of the recalled item, i.e. where it was presented in the preceding list (ranging from 1 to n, where n=listLength). 

Note that zeros can be used to pad the recalls matrix, since people probably made different numbers of recalls following each list. I believe intrusions can be marked with a negative number or 0.

As an example, this would be a valid recalls matrix from a participant who completed 4 lists and made a maximum of 7 recalls on any list:
[[16, 11, 13, 10, 9, 14, 5],
[12, 14, 6, 1, 8, 0, 0],
[5, 3, 2, 1, 5, -1, 0],
[10, 11, 14, 15, 16, 1, 2]]

The accompanying subjects array could then be [1, 1, 1, 1], similar to what you have.

Note that the repetition of item 5 and the intrusion (-1) in the third trial will be excluded when calculating the CRP.
